name: Daily Challenge Generator
on:
  workflow_dispatch: # This adds a manual "Run" button

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Daily Task
        uses: imjohnbo/issue-bot@v3.5
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          assignees: "abhi001-q"
          labels: "daily-challenge, easy, good first issue"
          title: "Day 1: Create a Responsive Navigation Bar"
          body: |
            ### 📝 Today's Challenge
            Create a simple, responsive navigation bar with a logo and three links (Home, About, Contact).
            
            ### 📂 Folder Location
            Save your solution in `challenges/easy/your-github-username/`
            
            ---
            *Maintain your streak! Submit a PR to get featured on the leaderboard.*
          token: ${{ secrets.GITHUB_TOKEN }}
